#############################################################################
# Makefile for building: diagramscene
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  diagramscene.pro
# Template: app
# Command: /opt/qt-5.5.1/bin/qmake -o Makefile diagramscene.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt-5.5.1/include -I/opt/qt-5.5.1/include/QtWidgets -I/opt/qt-5.5.1/include/QtGui -I/opt/qt-5.5.1/include/QtCore -I. -I/opt/qt-5.5.1/mkspecs/linux-g++
QMAKE         = /opt/qt-5.5.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = diagramscene1.0.0
DISTDIR = /u/data/u98/cs240/2015Fall/lab7-graphics-editor/cs240-lab7-src/.tmp/diagramscene1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-5.5.1/lib
LIBS          = $(SUBLIBS) -L/opt/qt-5.5.1/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		diagramitem.cpp \
		main.cpp \
		arrow.cpp \
		diagramtextitem.cpp \
		diagramscene.cpp qrc_diagramscene.cpp \
		moc_mainwindow.cpp \
		moc_diagramscene.cpp \
		moc_diagramtextitem.cpp
OBJECTS       = mainwindow.o \
		diagramitem.o \
		main.o \
		arrow.o \
		diagramtextitem.o \
		diagramscene.o \
		qrc_diagramscene.o \
		moc_mainwindow.o \
		moc_diagramscene.o \
		moc_diagramtextitem.o
DIST          = /opt/qt-5.5.1/mkspecs/features/spec_pre.prf \
		/usr/opt/qt-5.5.1/mkspecs/common/unix.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/linux.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/sanitize.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/gcc-base.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/gcc-base-unix.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/g++-base.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/g++-unix.conf \
		/opt/qt-5.5.1/mkspecs/qconfig.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_location.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-5.5.1/mkspecs/features/qt_functions.prf \
		/opt/qt-5.5.1/mkspecs/features/qt_config.prf \
		/opt/qt-5.5.1/mkspecs/linux-g++/qmake.conf \
		/opt/qt-5.5.1/mkspecs/features/spec_post.prf \
		/opt/qt-5.5.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-5.5.1/mkspecs/features/default_pre.prf \
		/opt/qt-5.5.1/mkspecs/features/resolve_config.prf \
		/opt/qt-5.5.1/mkspecs/features/default_post.prf \
		/opt/qt-5.5.1/mkspecs/features/warn_on.prf \
		/opt/qt-5.5.1/mkspecs/features/qt.prf \
		/opt/qt-5.5.1/mkspecs/features/resources.prf \
		/opt/qt-5.5.1/mkspecs/features/moc.prf \
		/opt/qt-5.5.1/mkspecs/features/unix/opengl.prf \
		/opt/qt-5.5.1/mkspecs/features/uic.prf \
		/opt/qt-5.5.1/mkspecs/features/unix/thread.prf \
		/opt/qt-5.5.1/mkspecs/features/testcase_targets.prf \
		/opt/qt-5.5.1/mkspecs/features/exceptions.prf \
		/opt/qt-5.5.1/mkspecs/features/yacc.prf \
		/opt/qt-5.5.1/mkspecs/features/lex.prf \
		diagramscene.pro mainwindow.h \
		diagramitem.h \
		diagramscene.h \
		arrow.h \
		diagramtextitem.h mainwindow.cpp \
		diagramitem.cpp \
		main.cpp \
		arrow.cpp \
		diagramtextitem.cpp \
		diagramscene.cpp
QMAKE_TARGET  = diagramscene
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = diagramscene


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: diagramscene.pro /opt/qt-5.5.1/mkspecs/linux-g++/qmake.conf /opt/qt-5.5.1/mkspecs/features/spec_pre.prf \
		/usr/opt/qt-5.5.1/mkspecs/common/unix.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/linux.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/sanitize.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/gcc-base.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/gcc-base-unix.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/g++-base.conf \
		/usr/opt/qt-5.5.1/mkspecs/common/g++-unix.conf \
		/opt/qt-5.5.1/mkspecs/qconfig.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_core.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_help.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_location.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_network.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_script.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt-5.5.1/mkspecs/features/qt_functions.prf \
		/opt/qt-5.5.1/mkspecs/features/qt_config.prf \
		/opt/qt-5.5.1/mkspecs/linux-g++/qmake.conf \
		/opt/qt-5.5.1/mkspecs/features/spec_post.prf \
		/opt/qt-5.5.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-5.5.1/mkspecs/features/default_pre.prf \
		/opt/qt-5.5.1/mkspecs/features/resolve_config.prf \
		/opt/qt-5.5.1/mkspecs/features/default_post.prf \
		/opt/qt-5.5.1/mkspecs/features/warn_on.prf \
		/opt/qt-5.5.1/mkspecs/features/qt.prf \
		/opt/qt-5.5.1/mkspecs/features/resources.prf \
		/opt/qt-5.5.1/mkspecs/features/moc.prf \
		/opt/qt-5.5.1/mkspecs/features/unix/opengl.prf \
		/opt/qt-5.5.1/mkspecs/features/uic.prf \
		/opt/qt-5.5.1/mkspecs/features/unix/thread.prf \
		/opt/qt-5.5.1/mkspecs/features/testcase_targets.prf \
		/opt/qt-5.5.1/mkspecs/features/exceptions.prf \
		/opt/qt-5.5.1/mkspecs/features/yacc.prf \
		/opt/qt-5.5.1/mkspecs/features/lex.prf \
		diagramscene.pro \
		diagramscene.qrc \
		/opt/qt-5.5.1/lib/libQt5Widgets.prl \
		/opt/qt-5.5.1/lib/libQt5Gui.prl \
		/opt/qt-5.5.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile diagramscene.pro
/opt/qt-5.5.1/mkspecs/features/spec_pre.prf:
/usr/opt/qt-5.5.1/mkspecs/common/unix.conf:
/usr/opt/qt-5.5.1/mkspecs/common/linux.conf:
/usr/opt/qt-5.5.1/mkspecs/common/sanitize.conf:
/usr/opt/qt-5.5.1/mkspecs/common/gcc-base.conf:
/usr/opt/qt-5.5.1/mkspecs/common/gcc-base-unix.conf:
/usr/opt/qt-5.5.1/mkspecs/common/g++-base.conf:
/usr/opt/qt-5.5.1/mkspecs/common/g++-unix.conf:
/opt/qt-5.5.1/mkspecs/qconfig.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcollision_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_core.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_help.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_location.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_network.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_script.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt-5.5.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt-5.5.1/mkspecs/features/qt_functions.prf:
/opt/qt-5.5.1/mkspecs/features/qt_config.prf:
/opt/qt-5.5.1/mkspecs/linux-g++/qmake.conf:
/opt/qt-5.5.1/mkspecs/features/spec_post.prf:
/opt/qt-5.5.1/mkspecs/features/exclusive_builds.prf:
/opt/qt-5.5.1/mkspecs/features/default_pre.prf:
/opt/qt-5.5.1/mkspecs/features/resolve_config.prf:
/opt/qt-5.5.1/mkspecs/features/default_post.prf:
/opt/qt-5.5.1/mkspecs/features/warn_on.prf:
/opt/qt-5.5.1/mkspecs/features/qt.prf:
/opt/qt-5.5.1/mkspecs/features/resources.prf:
/opt/qt-5.5.1/mkspecs/features/moc.prf:
/opt/qt-5.5.1/mkspecs/features/unix/opengl.prf:
/opt/qt-5.5.1/mkspecs/features/uic.prf:
/opt/qt-5.5.1/mkspecs/features/unix/thread.prf:
/opt/qt-5.5.1/mkspecs/features/testcase_targets.prf:
/opt/qt-5.5.1/mkspecs/features/exceptions.prf:
/opt/qt-5.5.1/mkspecs/features/yacc.prf:
/opt/qt-5.5.1/mkspecs/features/lex.prf:
diagramscene.pro:
diagramscene.qrc:
/opt/qt-5.5.1/lib/libQt5Widgets.prl:
/opt/qt-5.5.1/lib/libQt5Gui.prl:
/opt/qt-5.5.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile diagramscene.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents diagramscene.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h diagramitem.h diagramscene.h arrow.h diagramtextitem.h $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.cpp diagramitem.cpp main.cpp arrow.cpp diagramtextitem.cpp diagramscene.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_diagramscene.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_diagramscene.cpp
qrc_diagramscene.cpp: diagramscene.qrc \
		images/italic.png \
		images/floodfill.png \
		images/underline.png \
		images/background2.png \
		images/textpointer.png \
		images/sendtoback.png \
		images/pointer.png \
		images/background1.png \
		images/linecolor.png \
		images/bringtofront.png \
		images/background4.png \
		images/delete.png \
		images/linepointer.png \
		images/bold.png \
		images/background3.png
	/opt/qt-5.5.1/bin/rcc -name diagramscene diagramscene.qrc -o qrc_diagramscene.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_diagramscene.cpp moc_diagramtextitem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_diagramscene.cpp moc_diagramtextitem.cpp
moc_mainwindow.cpp: diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtCore/QList \
		/opt/qt-5.5.1/include/QtWidgets/QMainWindow \
		/opt/qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/opt/qt-5.5.1/include/QtWidgets/qwidget.h \
		/opt/qt-5.5.1/include/QtGui/qpalette.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		/opt/qt-5.5.1/include/QtGui/qfontmetrics.h \
		/opt/qt-5.5.1/include/QtGui/qfontinfo.h \
		/opt/qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.5.1/include/QtGui/qcursor.h \
		/opt/qt-5.5.1/include/QtGui/qkeysequence.h \
		/opt/qt-5.5.1/include/QtGui/qevent.h \
		/opt/qt-5.5.1/include/QtCore/qurl.h \
		/opt/qt-5.5.1/include/QtCore/qurlquery.h \
		/opt/qt-5.5.1/include/QtCore/qfile.h \
		/opt/qt-5.5.1/include/QtCore/qfiledevice.h \
		/opt/qt-5.5.1/include/QtGui/qvector2d.h \
		/opt/qt-5.5.1/include/QtGui/qtouchdevice.h \
		/opt/qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/opt/qt-5.5.1/include/QtGui/qicon.h \
		mainwindow.h
	/opt/qt-5.5.1/bin/moc $(DEFINES) -I/opt/qt-5.5.1/mkspecs/linux-g++ -I/u/data/u98/cs240/2015Fall/lab7-graphics-editor/cs240-lab7-src -I/opt/qt-5.5.1/include -I/opt/qt-5.5.1/include/QtWidgets -I/opt/qt-5.5.1/include/QtGui -I/opt/qt-5.5.1/include/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4 -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_diagramscene.cpp: diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtCore/QList \
		diagramtextitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsTextItem \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsScene \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsscene.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		diagramscene.h
	/opt/qt-5.5.1/bin/moc $(DEFINES) -I/opt/qt-5.5.1/mkspecs/linux-g++ -I/u/data/u98/cs240/2015Fall/lab7-graphics-editor/cs240-lab7-src -I/opt/qt-5.5.1/include -I/opt/qt-5.5.1/include/QtWidgets -I/opt/qt-5.5.1/include/QtGui -I/opt/qt-5.5.1/include/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4 -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include-fixed -I/usr/include diagramscene.h -o moc_diagramscene.cpp

moc_diagramtextitem.cpp: /opt/qt-5.5.1/include/QtWidgets/QGraphicsTextItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		diagramtextitem.h
	/opt/qt-5.5.1/bin/moc $(DEFINES) -I/opt/qt-5.5.1/mkspecs/linux-g++ -I/u/data/u98/cs240/2015Fall/lab7-graphics-editor/cs240-lab7-src -I/opt/qt-5.5.1/include -I/opt/qt-5.5.1/include/QtWidgets -I/opt/qt-5.5.1/include/QtGui -I/opt/qt-5.5.1/include/QtCore -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4 -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include/g++-v4/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include-fixed -I/usr/include diagramtextitem.h -o moc_diagramtextitem.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

mainwindow.o: mainwindow.cpp arrow.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsLineItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtCore/QList \
		diagramscene.h \
		diagramtextitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsTextItem \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsScene \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsscene.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		mainwindow.h \
		/opt/qt-5.5.1/include/QtWidgets/QMainWindow \
		/opt/qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/opt/qt-5.5.1/include/QtWidgets/qwidget.h \
		/opt/qt-5.5.1/include/QtGui/qpalette.h \
		/opt/qt-5.5.1/include/QtGui/qfontmetrics.h \
		/opt/qt-5.5.1/include/QtGui/qfontinfo.h \
		/opt/qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.5.1/include/QtGui/qcursor.h \
		/opt/qt-5.5.1/include/QtGui/qkeysequence.h \
		/opt/qt-5.5.1/include/QtGui/qevent.h \
		/opt/qt-5.5.1/include/QtCore/qurl.h \
		/opt/qt-5.5.1/include/QtCore/qurlquery.h \
		/opt/qt-5.5.1/include/QtCore/qfile.h \
		/opt/qt-5.5.1/include/QtCore/qfiledevice.h \
		/opt/qt-5.5.1/include/QtGui/qvector2d.h \
		/opt/qt-5.5.1/include/QtGui/qtouchdevice.h \
		/opt/qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/opt/qt-5.5.1/include/QtGui/qicon.h \
		/opt/qt-5.5.1/include/QtWidgets/QtWidgets \
		/opt/qt-5.5.1/include/QtWidgets/QtWidgetsDepends \
		/opt/qt-5.5.1/include/QtCore/QtCore \
		/opt/qt-5.5.1/include/QtCore/QtCoreDepends \
		/opt/qt-5.5.1/include/QtCore/qabstractanimation.h \
		/opt/qt-5.5.1/include/QtCore/qanimationgroup.h \
		/opt/qt-5.5.1/include/QtCore/qparallelanimationgroup.h \
		/opt/qt-5.5.1/include/QtCore/qpauseanimation.h \
		/opt/qt-5.5.1/include/QtCore/qpropertyanimation.h \
		/opt/qt-5.5.1/include/QtCore/qvariantanimation.h \
		/opt/qt-5.5.1/include/QtCore/qeasingcurve.h \
		/opt/qt-5.5.1/include/QtCore/qsequentialanimationgroup.h \
		/opt/qt-5.5.1/include/QtCore/qtextcodec.h \
		/opt/qt-5.5.1/include/QtCore/qendian.h \
		/opt/qt-5.5.1/include/QtCore/qlibraryinfo.h \
		/opt/qt-5.5.1/include/QtCore/qdatetime.h \
		/opt/qt-5.5.1/include/QtCore/qbuffer.h \
		/opt/qt-5.5.1/include/QtCore/qdir.h \
		/opt/qt-5.5.1/include/QtCore/qfileinfo.h \
		/opt/qt-5.5.1/include/QtCore/qdiriterator.h \
		/opt/qt-5.5.1/include/QtCore/qfileselector.h \
		/opt/qt-5.5.1/include/QtCore/QObject \
		/opt/qt-5.5.1/include/QtCore/QStringList \
		/opt/qt-5.5.1/include/QtCore/qfilesystemwatcher.h \
		/opt/qt-5.5.1/include/QtCore/qlockfile.h \
		/opt/qt-5.5.1/include/QtCore/qloggingcategory.h \
		/opt/qt-5.5.1/include/QtCore/qprocess.h \
		/opt/qt-5.5.1/include/QtCore/qresource.h \
		/opt/qt-5.5.1/include/QtCore/qsavefile.h \
		/opt/qt-5.5.1/include/QtCore/qsettings.h \
		/opt/qt-5.5.1/include/QtCore/qstandardpaths.h \
		/opt/qt-5.5.1/include/QtCore/qstorageinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtemporarydir.h \
		/opt/qt-5.5.1/include/QtCore/QScopedPointer \
		/opt/qt-5.5.1/include/QtCore/qtemporaryfile.h \
		/opt/qt-5.5.1/include/QtCore/qabstractitemmodel.h \
		/opt/qt-5.5.1/include/QtCore/qabstractproxymodel.h \
		/opt/qt-5.5.1/include/QtCore/qidentityproxymodel.h \
		/opt/qt-5.5.1/include/QtCore/qitemselectionmodel.h \
		/opt/qt-5.5.1/include/QtCore/qsortfilterproxymodel.h \
		/opt/qt-5.5.1/include/QtCore/qstringlistmodel.h \
		/opt/qt-5.5.1/include/QtCore/qjsonarray.h \
		/opt/qt-5.5.1/include/QtCore/qjsonvalue.h \
		/opt/qt-5.5.1/include/QtCore/qjsondocument.h \
		/opt/qt-5.5.1/include/QtCore/qjsonobject.h \
		/opt/qt-5.5.1/include/QtCore/qabstracteventdispatcher.h \
		/opt/qt-5.5.1/include/QtCore/qeventloop.h \
		/opt/qt-5.5.1/include/QtCore/qabstractnativeeventfilter.h \
		/opt/qt-5.5.1/include/QtCore/qbasictimer.h \
		/opt/qt-5.5.1/include/QtCore/qcoreapplication.h \
		/opt/qt-5.5.1/include/QtCore/qmath.h \
		/opt/qt-5.5.1/include/QtCore/qmetaobject.h \
		/opt/qt-5.5.1/include/QtCore/qmimedata.h \
		/opt/qt-5.5.1/include/QtCore/qobjectcleanuphandler.h \
		/opt/qt-5.5.1/include/QtCore/qpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedmemory.h \
		/opt/qt-5.5.1/include/QtCore/qsignalmapper.h \
		/opt/qt-5.5.1/include/QtCore/qsocketnotifier.h \
		/opt/qt-5.5.1/include/QtCore/qsystemsemaphore.h \
		/opt/qt-5.5.1/include/QtCore/qtimer.h \
		/opt/qt-5.5.1/include/QtCore/qtranslator.h \
		/opt/qt-5.5.1/include/QtCore/qwineventnotifier.h \
		/opt/qt-5.5.1/include/QtCore/qmimedatabase.h \
		/opt/qt-5.5.1/include/QtCore/qmimetype.h \
		/opt/qt-5.5.1/include/QtCore/qfactoryinterface.h \
		/opt/qt-5.5.1/include/QtCore/qlibrary.h \
		/opt/qt-5.5.1/include/QtCore/qplugin.h \
		/opt/qt-5.5.1/include/QtCore/qpluginloader.h \
		/opt/qt-5.5.1/include/QtCore/quuid.h \
		/opt/qt-5.5.1/include/QtCore/qabstractstate.h \
		/opt/qt-5.5.1/include/QtCore/qabstracttransition.h \
		/opt/qt-5.5.1/include/QtCore/qeventtransition.h \
		/opt/qt-5.5.1/include/QtCore/qfinalstate.h \
		/opt/qt-5.5.1/include/QtCore/qhistorystate.h \
		/opt/qt-5.5.1/include/QtCore/qsignaltransition.h \
		/opt/qt-5.5.1/include/QtCore/qstate.h \
		/opt/qt-5.5.1/include/QtCore/qstatemachine.h \
		/opt/qt-5.5.1/include/QtCore/qexception.h \
		/opt/qt-5.5.1/include/QtCore/qfuture.h \
		/opt/qt-5.5.1/include/QtCore/qfutureinterface.h \
		/opt/qt-5.5.1/include/QtCore/qrunnable.h \
		/opt/qt-5.5.1/include/QtCore/qresultstore.h \
		/opt/qt-5.5.1/include/QtCore/qfuturesynchronizer.h \
		/opt/qt-5.5.1/include/QtCore/qfuturewatcher.h \
		/opt/qt-5.5.1/include/QtCore/qreadwritelock.h \
		/opt/qt-5.5.1/include/QtCore/qsemaphore.h \
		/opt/qt-5.5.1/include/QtCore/qthread.h \
		/opt/qt-5.5.1/include/QtCore/qthreadpool.h \
		/opt/qt-5.5.1/include/QtCore/qthreadstorage.h \
		/opt/qt-5.5.1/include/QtCore/qwaitcondition.h \
		/opt/qt-5.5.1/include/QtCore/qarraydataops.h \
		/opt/qt-5.5.1/include/QtCore/qarraydatapointer.h \
		/opt/qt-5.5.1/include/QtCore/qbitarray.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraymatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcache.h \
		/opt/qt-5.5.1/include/QtCore/qcollator.h \
		/opt/qt-5.5.1/include/QtCore/qcommandlineoption.h \
		/opt/qt-5.5.1/include/QtCore/qcommandlineparser.h \
		/opt/qt-5.5.1/include/QtCore/qcryptographichash.h \
		/opt/qt-5.5.1/include/QtCore/qelapsedtimer.h \
		/opt/qt-5.5.1/include/QtCore/qlinkedlist.h \
		/opt/qt-5.5.1/include/QtCore/qmessageauthenticationcode.h \
		/opt/qt-5.5.1/include/QtCore/qqueue.h \
		/opt/qt-5.5.1/include/QtCore/qregularexpression.h \
		/opt/qt-5.5.1/include/QtCore/qscopedvaluerollback.h \
		/opt/qt-5.5.1/include/QtCore/qstack.h \
		/opt/qt-5.5.1/include/QtCore/qtextboundaryfinder.h \
		/opt/qt-5.5.1/include/QtCore/qtimeline.h \
		/opt/qt-5.5.1/include/QtCore/qtimezone.h \
		/opt/qt-5.5.1/include/QtCore/qxmlstream.h \
		/opt/qt-5.5.1/include/QtCore/qtcoreversion.h \
		/opt/qt-5.5.1/include/QtGui/QtGui \
		/opt/qt-5.5.1/include/QtGui/QtGuiDepends \
		/opt/qt-5.5.1/include/QtGui/qaccessible.h \
		/opt/qt-5.5.1/include/QtGui/qaccessiblebridge.h \
		/opt/qt-5.5.1/include/QtGui/qaccessibleobject.h \
		/opt/qt-5.5.1/include/QtGui/qaccessibleplugin.h \
		/opt/qt-5.5.1/include/QtGui/qbitmap.h \
		/opt/qt-5.5.1/include/QtGui/qiconengine.h \
		/opt/qt-5.5.1/include/QtGui/qiconengineplugin.h \
		/opt/qt-5.5.1/include/QtGui/qimageiohandler.h \
		/opt/qt-5.5.1/include/QtGui/qimagereader.h \
		/opt/qt-5.5.1/include/QtGui/qimagewriter.h \
		/opt/qt-5.5.1/include/QtGui/qmovie.h \
		/opt/qt-5.5.1/include/QtGui/qpicture.h \
		/opt/qt-5.5.1/include/QtGui/qpictureformatplugin.h \
		/opt/qt-5.5.1/include/QtGui/qpixmapcache.h \
		/opt/qt-5.5.1/include/QtGui/qstandarditemmodel.h \
		/opt/qt-5.5.1/include/QtGui/qclipboard.h \
		/opt/qt-5.5.1/include/QtGui/qdrag.h \
		/opt/qt-5.5.1/include/QtGui/qgenericplugin.h \
		/opt/qt-5.5.1/include/QtGui/qgenericpluginfactory.h \
		/opt/qt-5.5.1/include/QtGui/qguiapplication.h \
		/opt/qt-5.5.1/include/QtGui/qinputmethod.h \
		/opt/qt-5.5.1/include/QtGui/qoffscreensurface.h \
		/opt/qt-5.5.1/include/QtGui/qsurface.h \
		/opt/qt-5.5.1/include/QtGui/qsurfaceformat.h \
		/opt/qt-5.5.1/include/QtGui/qopenglcontext.h \
		/opt/qt-5.5.1/include/QtGui/QSurfaceFormat \
		/opt/qt-5.5.1/include/QtGui/qopengl.h \
		/opt/qt-5.5.1/include/QtCore/qt_windows.h \
		/opt/qt-5.5.1/include/QtGui/qopengles2ext.h \
		/opt/qt-5.5.1/include/QtGui/qopenglext.h \
		/opt/qt-5.5.1/include/QtGui/qopenglversionfunctions.h \
		/opt/qt-5.5.1/include/QtGui/qopenglwindow.h \
		/opt/qt-5.5.1/include/QtGui/QPaintDeviceWindow \
		/opt/qt-5.5.1/include/QtGui/qpaintdevicewindow.h \
		/opt/qt-5.5.1/include/QtGui/QWindow \
		/opt/qt-5.5.1/include/QtGui/qwindow.h \
		/opt/qt-5.5.1/include/QtCore/QEvent \
		/opt/qt-5.5.1/include/QtCore/QMargins \
		/opt/qt-5.5.1/include/QtCore/QRect \
		/opt/qt-5.5.1/include/QtGui/QPaintDevice \
		/opt/qt-5.5.1/include/QtGui/QOpenGLContext \
		/opt/qt-5.5.1/include/QtGui/QImage \
		/opt/qt-5.5.1/include/QtGui/qrasterwindow.h \
		/opt/qt-5.5.1/include/QtGui/qscreen.h \
		/opt/qt-5.5.1/include/QtCore/QSize \
		/opt/qt-5.5.1/include/QtCore/QSizeF \
		/opt/qt-5.5.1/include/QtGui/QTransform \
		/opt/qt-5.5.1/include/QtGui/qsessionmanager.h \
		/opt/qt-5.5.1/include/QtGui/qstylehints.h \
		/opt/qt-5.5.1/include/QtGui/qgenericmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix4x4.h \
		/opt/qt-5.5.1/include/QtGui/qvector3d.h \
		/opt/qt-5.5.1/include/QtGui/qvector4d.h \
		/opt/qt-5.5.1/include/QtGui/qquaternion.h \
		/opt/qt-5.5.1/include/QtGui/qopenglbuffer.h \
		/opt/qt-5.5.1/include/QtGui/qopengldebug.h \
		/opt/qt-5.5.1/include/QtGui/qopenglframebufferobject.h \
		/opt/qt-5.5.1/include/QtGui/qopenglfunctions.h \
		/opt/qt-5.5.1/include/QtGui/qopenglpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qopenglpixeltransferoptions.h \
		/opt/qt-5.5.1/include/QtCore/QSharedDataPointer \
		/opt/qt-5.5.1/include/QtGui/qopenglshaderprogram.h \
		/opt/qt-5.5.1/include/QtGui/qopengltexture.h \
		/opt/qt-5.5.1/include/QtGui/qopengltimerquery.h \
		/opt/qt-5.5.1/include/QtGui/qopenglvertexarrayobject.h \
		/opt/qt-5.5.1/include/QtGui/qbackingstore.h \
		/opt/qt-5.5.1/include/QtGui/qpagedpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qpagelayout.h \
		/opt/qt-5.5.1/include/QtGui/qpagesize.h \
		/opt/qt-5.5.1/include/QtGui/qpaintengine.h \
		/opt/qt-5.5.1/include/QtGui/qpainter.h \
		/opt/qt-5.5.1/include/QtGui/qtextoption.h \
		/opt/qt-5.5.1/include/QtGui/qpdfwriter.h \
		/opt/qt-5.5.1/include/QtGui/qabstracttextdocumentlayout.h \
		/opt/qt-5.5.1/include/QtGui/qtextlayout.h \
		/opt/qt-5.5.1/include/QtGui/qtextformat.h \
		/opt/qt-5.5.1/include/QtGui/qglyphrun.h \
		/opt/qt-5.5.1/include/QtGui/qrawfont.h \
		/opt/qt-5.5.1/include/QtGui/qfontdatabase.h \
		/opt/qt-5.5.1/include/QtGui/qtextcursor.h \
		/opt/qt-5.5.1/include/QtGui/qtextdocument.h \
		/opt/qt-5.5.1/include/QtGui/qstatictext.h \
		/opt/qt-5.5.1/include/QtGui/qsyntaxhighlighter.h \
		/opt/qt-5.5.1/include/QtGui/qtextobject.h \
		/opt/qt-5.5.1/include/QtGui/qtextdocumentfragment.h \
		/opt/qt-5.5.1/include/QtGui/qtextdocumentwriter.h \
		/opt/qt-5.5.1/include/QtGui/qtextlist.h \
		/opt/qt-5.5.1/include/QtGui/qtexttable.h \
		/opt/qt-5.5.1/include/QtGui/qdesktopservices.h \
		/opt/qt-5.5.1/include/QtGui/qvalidator.h \
		/opt/qt-5.5.1/include/QtGui/qtguiversion.h \
		/opt/qt-5.5.1/include/QtWidgets/qaccessiblewidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qcolordialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qdialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qerrormessage.h \
		/opt/qt-5.5.1/include/QtWidgets/qfiledialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qfilesystemmodel.h \
		/opt/qt-5.5.1/include/QtWidgets/qfontdialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qinputdialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qlineedit.h \
		/opt/qt-5.5.1/include/QtWidgets/qframe.h \
		/opt/qt-5.5.1/include/QtWidgets/qmessagebox.h \
		/opt/qt-5.5.1/include/QtWidgets/qprogressdialog.h \
		/opt/qt-5.5.1/include/QtWidgets/qwizard.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicseffect.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsanchorlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicslayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsgridlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitemanimation.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicslinearlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicswidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicssceneevent.h \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicstransform.h \
		/opt/qt-5.5.1/include/QtGui/QVector3D \
		/opt/qt-5.5.1/include/QtGui/QMatrix4x4 \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsview.h \
		/opt/qt-5.5.1/include/QtWidgets/qscrollarea.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt-5.5.1/include/QtWidgets/qstyleoption.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractspinbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qslider.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractslider.h \
		/opt/qt-5.5.1/include/QtWidgets/qstyle.h \
		/opt/qt-5.5.1/include/QtWidgets/qtabbar.h \
		/opt/qt-5.5.1/include/QtWidgets/qrubberband.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractitemview.h \
		/opt/qt-5.5.1/include/QtWidgets/qcolumnview.h \
		/opt/qt-5.5.1/include/QtWidgets/qdatawidgetmapper.h \
		/opt/qt-5.5.1/include/QtWidgets/qdirmodel.h \
		/opt/qt-5.5.1/include/QtWidgets/qfileiconprovider.h \
		/opt/qt-5.5.1/include/QtWidgets/qheaderview.h \
		/opt/qt-5.5.1/include/QtWidgets/qitemdelegate.h \
		/opt/qt-5.5.1/include/QtWidgets/qitemeditorfactory.h \
		/opt/qt-5.5.1/include/QtWidgets/qlistview.h \
		/opt/qt-5.5.1/include/QtWidgets/qlistwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qstyleditemdelegate.h \
		/opt/qt-5.5.1/include/QtWidgets/qtableview.h \
		/opt/qt-5.5.1/include/QtWidgets/qtablewidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qtreeview.h \
		/opt/qt-5.5.1/include/QtWidgets/qtreewidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qtreewidgetitemiterator.h \
		/opt/qt-5.5.1/include/QtWidgets/qaction.h \
		/opt/qt-5.5.1/include/QtWidgets/qactiongroup.h \
		/opt/qt-5.5.1/include/QtWidgets/qapplication.h \
		/opt/qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qboxlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qlayoutitem.h \
		/opt/qt-5.5.1/include/QtWidgets/qgridlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qformlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/QLayout \
		/opt/qt-5.5.1/include/QtWidgets/qgesture.h \
		/opt/qt-5.5.1/include/QtWidgets/qgesturerecognizer.h \
		/opt/qt-5.5.1/include/QtWidgets/qopenglwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/QWidget \
		/opt/qt-5.5.1/include/QtWidgets/qshortcut.h \
		/opt/qt-5.5.1/include/QtWidgets/qstackedlayout.h \
		/opt/qt-5.5.1/include/QtWidgets/qtooltip.h \
		/opt/qt-5.5.1/include/QtWidgets/qwhatsthis.h \
		/opt/qt-5.5.1/include/QtWidgets/qwidgetaction.h \
		/opt/qt-5.5.1/include/QtWidgets/qkeyeventtransition.h \
		/opt/qt-5.5.1/include/QtWidgets/qmouseeventtransition.h \
		/opt/qt-5.5.1/include/QtWidgets/qcommonstyle.h \
		/opt/qt-5.5.1/include/QtWidgets/qdrawutil.h \
		/opt/qt-5.5.1/include/QtWidgets/qproxystyle.h \
		/opt/qt-5.5.1/include/QtWidgets/QCommonStyle \
		/opt/qt-5.5.1/include/QtWidgets/qstylefactory.h \
		/opt/qt-5.5.1/include/QtWidgets/qstylepainter.h \
		/opt/qt-5.5.1/include/QtWidgets/qstyleplugin.h \
		/opt/qt-5.5.1/include/QtWidgets/qcolormap.h \
		/opt/qt-5.5.1/include/QtWidgets/qcompleter.h \
		/opt/qt-5.5.1/include/QtWidgets/qscroller.h \
		/opt/qt-5.5.1/include/QtCore/QPointF \
		/opt/qt-5.5.1/include/QtWidgets/QScrollerProperties \
		/opt/qt-5.5.1/include/QtWidgets/qscrollerproperties.h \
		/opt/qt-5.5.1/include/QtCore/QMetaType \
		/opt/qt-5.5.1/include/QtCore/QVariant \
		/opt/qt-5.5.1/include/QtWidgets/qsystemtrayicon.h \
		/opt/qt-5.5.1/include/QtWidgets/qundogroup.h \
		/opt/qt-5.5.1/include/QtWidgets/qundostack.h \
		/opt/qt-5.5.1/include/QtWidgets/qundoview.h \
		/opt/qt-5.5.1/include/QtWidgets/qabstractbutton.h \
		/opt/qt-5.5.1/include/QtWidgets/qbuttongroup.h \
		/opt/qt-5.5.1/include/QtWidgets/qcalendarwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qcheckbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qcombobox.h \
		/opt/qt-5.5.1/include/QtWidgets/qcommandlinkbutton.h \
		/opt/qt-5.5.1/include/QtWidgets/qpushbutton.h \
		/opt/qt-5.5.1/include/QtWidgets/qdatetimeedit.h \
		/opt/qt-5.5.1/include/QtWidgets/qdial.h \
		/opt/qt-5.5.1/include/QtWidgets/qdialogbuttonbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qdockwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qfocusframe.h \
		/opt/qt-5.5.1/include/QtWidgets/qfontcombobox.h \
		/opt/qt-5.5.1/include/QtWidgets/qgroupbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qkeysequenceedit.h \
		/opt/qt-5.5.1/include/QtWidgets/qlabel.h \
		/opt/qt-5.5.1/include/QtWidgets/qlcdnumber.h \
		/opt/qt-5.5.1/include/QtWidgets/qmdiarea.h \
		/opt/qt-5.5.1/include/QtWidgets/qmdisubwindow.h \
		/opt/qt-5.5.1/include/QtWidgets/qmenu.h \
		/opt/qt-5.5.1/include/QtWidgets/qmenubar.h \
		/opt/qt-5.5.1/include/QtWidgets/qplaintextedit.h \
		/opt/qt-5.5.1/include/QtWidgets/qtextedit.h \
		/opt/qt-5.5.1/include/QtWidgets/qprogressbar.h \
		/opt/qt-5.5.1/include/QtWidgets/qradiobutton.h \
		/opt/qt-5.5.1/include/QtWidgets/qscrollbar.h \
		/opt/qt-5.5.1/include/QtWidgets/qsizegrip.h \
		/opt/qt-5.5.1/include/QtWidgets/qspinbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qsplashscreen.h \
		/opt/qt-5.5.1/include/QtWidgets/qsplitter.h \
		/opt/qt-5.5.1/include/QtWidgets/qstackedwidget.h \
		/opt/qt-5.5.1/include/QtWidgets/qstatusbar.h \
		/opt/qt-5.5.1/include/QtWidgets/qtextbrowser.h \
		/opt/qt-5.5.1/include/QtWidgets/qtoolbar.h \
		/opt/qt-5.5.1/include/QtWidgets/qtoolbox.h \
		/opt/qt-5.5.1/include/QtWidgets/qtoolbutton.h \
		/opt/qt-5.5.1/include/QtWidgets/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

diagramitem.o: diagramitem.cpp diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtCore/QList \
		arrow.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsLineItem \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsScene \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsscene.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsSceneContextMenuEvent \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicssceneevent.h \
		/opt/qt-5.5.1/include/QtWidgets/QMenu \
		/opt/qt-5.5.1/include/QtWidgets/qmenu.h \
		/opt/qt-5.5.1/include/QtWidgets/qwidget.h \
		/opt/qt-5.5.1/include/QtGui/qpalette.h \
		/opt/qt-5.5.1/include/QtGui/qfontmetrics.h \
		/opt/qt-5.5.1/include/QtGui/qfontinfo.h \
		/opt/qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.5.1/include/QtGui/qcursor.h \
		/opt/qt-5.5.1/include/QtGui/qkeysequence.h \
		/opt/qt-5.5.1/include/QtGui/qevent.h \
		/opt/qt-5.5.1/include/QtCore/qurl.h \
		/opt/qt-5.5.1/include/QtCore/qurlquery.h \
		/opt/qt-5.5.1/include/QtCore/qfile.h \
		/opt/qt-5.5.1/include/QtCore/qfiledevice.h \
		/opt/qt-5.5.1/include/QtGui/qvector2d.h \
		/opt/qt-5.5.1/include/QtGui/qtouchdevice.h \
		/opt/qt-5.5.1/include/QtGui/qicon.h \
		/opt/qt-5.5.1/include/QtWidgets/qaction.h \
		/opt/qt-5.5.1/include/QtWidgets/qactiongroup.h \
		/opt/qt-5.5.1/include/QtGui/QPainter \
		/opt/qt-5.5.1/include/QtGui/qpainter.h \
		/opt/qt-5.5.1/include/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramitem.o diagramitem.cpp

main.o: main.cpp mainwindow.h \
		diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtCore/QList \
		/opt/qt-5.5.1/include/QtWidgets/QMainWindow \
		/opt/qt-5.5.1/include/QtWidgets/qmainwindow.h \
		/opt/qt-5.5.1/include/QtWidgets/qwidget.h \
		/opt/qt-5.5.1/include/QtGui/qpalette.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		/opt/qt-5.5.1/include/QtGui/qfontmetrics.h \
		/opt/qt-5.5.1/include/QtGui/qfontinfo.h \
		/opt/qt-5.5.1/include/QtWidgets/qsizepolicy.h \
		/opt/qt-5.5.1/include/QtGui/qcursor.h \
		/opt/qt-5.5.1/include/QtGui/qkeysequence.h \
		/opt/qt-5.5.1/include/QtGui/qevent.h \
		/opt/qt-5.5.1/include/QtCore/qurl.h \
		/opt/qt-5.5.1/include/QtCore/qurlquery.h \
		/opt/qt-5.5.1/include/QtCore/qfile.h \
		/opt/qt-5.5.1/include/QtCore/qfiledevice.h \
		/opt/qt-5.5.1/include/QtGui/qvector2d.h \
		/opt/qt-5.5.1/include/QtGui/qtouchdevice.h \
		/opt/qt-5.5.1/include/QtWidgets/qtabwidget.h \
		/opt/qt-5.5.1/include/QtGui/qicon.h \
		/opt/qt-5.5.1/include/QtWidgets/QApplication \
		/opt/qt-5.5.1/include/QtWidgets/qapplication.h \
		/opt/qt-5.5.1/include/QtCore/qcoreapplication.h \
		/opt/qt-5.5.1/include/QtCore/qeventloop.h \
		/opt/qt-5.5.1/include/QtWidgets/qdesktopwidget.h \
		/opt/qt-5.5.1/include/QtGui/qguiapplication.h \
		/opt/qt-5.5.1/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

arrow.o: arrow.cpp arrow.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsLineItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtCore/QList \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtGui/QPainter \
		/opt/qt-5.5.1/include/QtGui/qpainter.h \
		/opt/qt-5.5.1/include/QtGui/qtextoption.h \
		/opt/qt-5.5.1/include/QtGui/qfontinfo.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		/opt/qt-5.5.1/include/QtGui/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrow.o arrow.cpp

diagramtextitem.o: diagramtextitem.cpp diagramtextitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsTextItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		diagramscene.h \
		diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtCore/QList \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsScene \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsscene.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramtextitem.o diagramtextitem.cpp

diagramscene.o: diagramscene.cpp diagramscene.h \
		diagramitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsPixmapItem \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsitem.h \
		/opt/qt-5.5.1/include/QtCore/qglobal.h \
		/opt/qt-5.5.1/include/QtCore/qconfig.h \
		/opt/qt-5.5.1/include/QtCore/qfeatures.h \
		/opt/qt-5.5.1/include/QtCore/qsystemdetection.h \
		/opt/qt-5.5.1/include/QtCore/qprocessordetection.h \
		/opt/qt-5.5.1/include/QtCore/qcompilerdetection.h \
		/opt/qt-5.5.1/include/QtCore/qtypeinfo.h \
		/opt/qt-5.5.1/include/QtCore/qtypetraits.h \
		/opt/qt-5.5.1/include/QtCore/qsysinfo.h \
		/opt/qt-5.5.1/include/QtCore/qlogging.h \
		/opt/qt-5.5.1/include/QtCore/qflags.h \
		/opt/qt-5.5.1/include/QtCore/qatomic.h \
		/opt/qt-5.5.1/include/QtCore/qbasicatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_bootstrap.h \
		/opt/qt-5.5.1/include/QtCore/qgenericatomic.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_cxx11.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_gcc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_msvc.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv7.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv6.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_armv5.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_ia64.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_mips.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_x86.h \
		/opt/qt-5.5.1/include/QtCore/qatomic_unix.h \
		/opt/qt-5.5.1/include/QtCore/qglobalstatic.h \
		/opt/qt-5.5.1/include/QtCore/qmutex.h \
		/opt/qt-5.5.1/include/QtCore/qnumeric.h \
		/opt/qt-5.5.1/include/QtCore/qobject.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs.h \
		/opt/qt-5.5.1/include/QtCore/qnamespace.h \
		/opt/qt-5.5.1/include/QtCore/qobjectdefs_impl.h \
		/opt/qt-5.5.1/include/QtCore/qstring.h \
		/opt/qt-5.5.1/include/QtCore/qchar.h \
		/opt/qt-5.5.1/include/QtCore/qbytearray.h \
		/opt/qt-5.5.1/include/QtCore/qrefcount.h \
		/opt/qt-5.5.1/include/QtCore/qarraydata.h \
		/opt/qt-5.5.1/include/QtCore/qstringbuilder.h \
		/opt/qt-5.5.1/include/QtCore/qlist.h \
		/opt/qt-5.5.1/include/QtCore/qalgorithms.h \
		/opt/qt-5.5.1/include/QtCore/qiterator.h \
		/opt/qt-5.5.1/include/QtCore/qbytearraylist.h \
		/opt/qt-5.5.1/include/QtCore/qstringlist.h \
		/opt/qt-5.5.1/include/QtCore/qregexp.h \
		/opt/qt-5.5.1/include/QtCore/qstringmatcher.h \
		/opt/qt-5.5.1/include/QtCore/qcoreevent.h \
		/opt/qt-5.5.1/include/QtCore/qscopedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qmetatype.h \
		/opt/qt-5.5.1/include/QtCore/qvarlengtharray.h \
		/opt/qt-5.5.1/include/QtCore/qcontainerfwd.h \
		/opt/qt-5.5.1/include/QtCore/qisenum.h \
		/opt/qt-5.5.1/include/QtCore/qobject_impl.h \
		/opt/qt-5.5.1/include/QtCore/qvariant.h \
		/opt/qt-5.5.1/include/QtCore/qmap.h \
		/opt/qt-5.5.1/include/QtCore/qpair.h \
		/opt/qt-5.5.1/include/QtCore/qdebug.h \
		/opt/qt-5.5.1/include/QtCore/qhash.h \
		/opt/qt-5.5.1/include/QtCore/qtextstream.h \
		/opt/qt-5.5.1/include/QtCore/qiodevice.h \
		/opt/qt-5.5.1/include/QtCore/qlocale.h \
		/opt/qt-5.5.1/include/QtCore/qshareddata.h \
		/opt/qt-5.5.1/include/QtCore/qvector.h \
		/opt/qt-5.5.1/include/QtCore/qpoint.h \
		/opt/qt-5.5.1/include/QtCore/qset.h \
		/opt/qt-5.5.1/include/QtCore/qcontiguouscache.h \
		/opt/qt-5.5.1/include/QtCore/qrect.h \
		/opt/qt-5.5.1/include/QtCore/qmargins.h \
		/opt/qt-5.5.1/include/QtCore/qsize.h \
		/opt/qt-5.5.1/include/QtGui/qpainterpath.h \
		/opt/qt-5.5.1/include/QtGui/qmatrix.h \
		/opt/qt-5.5.1/include/QtGui/qpolygon.h \
		/opt/qt-5.5.1/include/QtGui/qregion.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs.h \
		/opt/qt-5.5.1/include/QtGui/qwindowdefs_win.h \
		/opt/qt-5.5.1/include/QtCore/qdatastream.h \
		/opt/qt-5.5.1/include/QtCore/qline.h \
		/opt/qt-5.5.1/include/QtGui/qpixmap.h \
		/opt/qt-5.5.1/include/QtGui/qpaintdevice.h \
		/opt/qt-5.5.1/include/QtGui/qcolor.h \
		/opt/qt-5.5.1/include/QtGui/qrgb.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer.h \
		/opt/qt-5.5.1/include/QtCore/qsharedpointer_impl.h \
		/opt/qt-5.5.1/include/QtGui/qimage.h \
		/opt/qt-5.5.1/include/QtGui/qtransform.h \
		/opt/qt-5.5.1/include/QtGui/qpixelformat.h \
		/opt/qt-5.5.1/include/QtCore/QList \
		diagramtextitem.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsTextItem \
		/opt/qt-5.5.1/include/QtGui/QPen \
		/opt/qt-5.5.1/include/QtGui/qpen.h \
		/opt/qt-5.5.1/include/QtGui/qbrush.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsScene \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicsscene.h \
		/opt/qt-5.5.1/include/QtGui/qfont.h \
		arrow.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsLineItem \
		/opt/qt-5.5.1/include/QtGui/QTextCursor \
		/opt/qt-5.5.1/include/QtGui/qtextcursor.h \
		/opt/qt-5.5.1/include/QtGui/qtextformat.h \
		/opt/qt-5.5.1/include/QtGui/qtextoption.h \
		/opt/qt-5.5.1/include/QtWidgets/QGraphicsSceneMouseEvent \
		/opt/qt-5.5.1/include/QtWidgets/qgraphicssceneevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscene.o diagramscene.cpp

qrc_diagramscene.o: qrc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_diagramscene.o qrc_diagramscene.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_diagramscene.o: moc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramscene.o moc_diagramscene.cpp

moc_diagramtextitem.o: moc_diagramtextitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramtextitem.o moc_diagramtextitem.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene || mkdir -p $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qt-5.5.1/examples/widgets/graphicsview/diagramscene/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

